version: '3.9'

name: tarim

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: tarim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
  

  minio:
    image: minio/minio:RELEASE.2024-05-07T06-41-25Z

    ports:
      - 9000:9000
      - 9001:9001

    volumes:
      - minio_storage:/data

    environment:
      MINIO_ROOT_USER: tarim
      MINIO_ROOT_PASSWORD: passwordAdmin

    command: minio server --console-address ":9001" /data

    
volumes:
  minio_storage:




      